Feature/check biometric
OutSystems/cordova-plugin-touchid pull request #2
Opened 2019-06-11 19:59 UTC by BrunoJAzevedo

Adding ability to check what kind of Biometry the device has. If it is TouchID the int 1 will be sent to the callback. If it's FaceID it will be sent the int 2

2019-06-11 22:02 UTC, Chuckytuh requested changes
Could the new feature be documented on README?

2019-07-16 11:04 UTC, vmfo22 commented
@BrunoJAzevedo will review the feedback received?

2019-07-22 13:10 UTC, BrunoJAzevedo commented
@vmfo22 @Chuckytuh Done
Sorry for the delay

2019-07-22 16:16 UTC, Chuckytuh approved these changes

2019-07-23 08:54 UTC, vmfo22 approved these changes

2019-08-26 16:26 UTC, luissilvaos approved these changes

2019-08-26 16:27 UTC, merged